## Trabajo Homicidios

```{r}
library(sqldf)
library(ggplot2)


# Movil Victima con mayores homicidios haciendo distincion de genero

Datos <- sqldf("SELECT CASE WHEN [Móvil Victima] !='-' THEN [Móvil Victima] ELSE 'DESCONOCIDO' END AS [Móvil Victima] , sexo,  count(sexo) AS Cantidad FROM Homicidios WHERE Departamento = 'VALLE' AND Municipio = 'CALI (CT)' group by sexo, [Móvil Victima]")
#Visualizar Consulta#
#View(Datos)

#Graficar
ggplot(Datos, aes(x = `Móvil Victima`, y=Cantidad, fill =Sexo))+
  #Rango de datos
  scale_y_continuous(limit = c(0,1200))+
  #Separa la columna de acuerdo al género
  geom_col(position='dodge' ) +
  labs( title = "Víctimas de homicidio según el género y el tipo de movilidad\n", x= "Tipo de movilidad" , y ="Cantidad de víctimas" )+
  #Valores encima de las columnas
  geom_text(aes(y = Cantidad, label = Cantidad), 
            position = position_dodge(width = 0.9), size=2.5, vjust=-1, hjust=0.5 ,col="black")+
  #Eje X vertical, y personaliza el título
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 8), axis.title.x = element_text(size = 8),
    axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 8),
    plot.title = element_text(size = 10, face = "bold", color = "black",hjust = 0.5)
  )


#--------------------------------------
```

```{r}
library(sqldf)
library(ggplot2)

#Top 5 Barrios con mayor cantidad homicidios en la ciudad de Cali

test2 <- sqldf(

"SELECT A.*, SUM(CONCA) AS total FROM
(SELECT Barrio, Count(Barrio) AS CONCA
FROM Homicidios
WHERE Departamento = 'VALLE' AND Municipio = 'CALI (CT)'
Group By Barrio
Order By 2 DESC limit 5)A "


)
View(test2)

test3 <- sqldf("SELECT Barrio, Count(Barrio) AS CONCA, 
Count(Barrio)   /( SELECT (SUM(CONCA) *1.0) FROM
(SELECT Barrio, Count(Barrio) AS CONCA
FROM Homicidios
WHERE Departamento = 'VALLE' AND Municipio = 'CALI (CT)'
Group By Barrio
Order By 2 DESC limit 5)A)*100   AS Total 
FROM Homicidios
WHERE Departamento = 'VALLE' AND Municipio = 'CALI (CT)'
Group By Barrio
Order By 2 DESC limit 5")
View(test3)


ggplot(test2,aes(x=Barrio, y=Cantidad, fill=Barrio))+geom_col(position='dodge')+
labs( title = "Top 5 Barrios con mayor cantidad de homicidios en la ciudad de Cali\n", x= "Barrio" , y ="Cantidad de víctimas" )+
geom_text(aes(y = Cantidad,label = Cantidad), 
            position = position_dodge(width = 0.9), size=2.5, vjust=-1, hjust=0.5 ,col="black")+
#Rango de datos
scale_y_continuous(limit = c(0,40))+
theme(
  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 8), axis.title.x = element_text(size = 8),
  axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 8),
  plot.title = element_text(size = 10, face = "bold", color = "black")
)

#--------------------------------------
```
